'use strict';

/**
 * Initialize default options.
 */

module.exports = function(app) {
  app.disable('default routes');
  
  app.option({
    toc: {append: '\n\n_(Table of contents generated by [update])_'}
  });

  app.option('view engine', '*');
  app.option('layoutDelims', ['{%', '%}']);
  app.option('escapeDelims', ['<%%', '<%']);
};
