#!/usr/bin/env fish

# Borrowed from gulp:

# Usage:
#
# To enable fish <tab> completion for generate, add the following line to
# your ~/.config/fish/config.fish file:
#
# generate --completion=fish | source

complete -c generate -a "(generate --tasks-simple)" -f
