#!/bin/zsh

# Borrowed from grunt-cli, by way of gulp
# http://gruntjs.com/
#
# Copyright (c) 2012 Tyler Kellen, contributors
# Licensed under the MIT license.
# https://github.com/gruntjs/grunt/blob/master/LICENSE-MIT

# Usage:
#
# To enable zsh <tab> completion for generate, add the following line (minus the
# leading #, which is the zsh comment character) to your ~/.zshrc file:
#
# eval "$(generate --completion=zsh)"

# Enable zsh autocompletion.
function _generate_completion() {
  # Grab tasks
  compls=$(generate --tasks-simple)
  completions=(${=compls})
  compadd -- $completions
}

compdef _generate_completion generate
